language: php

php:
  - 7.2

install:
  - composer install --prefer-dist --optimize-autoloader --quiet

notifications:
  email:
    recipients:
      - cscolabear+travis-org@gmail.com
    on_success: change
    on_failure: always

script: vendor/bin/phpunit -c phpunit.xml --coverage-text
